### ISSUE TITLE
2 Routes shown

### ISSUE THREAD

**Issue by indicatelovelace** [Christophgru/WebEng2#21]
Old Route is still visible after new route is selected.

**Comment by Christophgru** [comment]
Wahrscheinlich ist dieser Code in MapComponent.jsx (l. 107) nicht mehr durchlaufen worden:

// Clear existing layers on the map
                mapRef.current.eachLayer((layer) => {
                    if (!(layer instanceof L.TileLayer)) {
                        mapRef.current.removeLayer(layer);
                    }
                });
                
 der ist für genau das zuständig

**Comment by Christophgru** [comment]
In der tat hat dies den fehler beseitigt
