### ISSUE TITLE
Searching "Rehmen"  crashes the Application

### ISSUE THREAD

**Issue by Christophgru** [Christophgru/WebEng2#9]
At map component, after 

"const data = await getWikipediaPageInfo(destinationMarker[0], destinationMarker[1]);"

check data for legitimacy before writing it to setDestinationInfo()
If no nice result, skip forward to "setCurrentDestination(destinationMarker.toString()); " or write "No Data" into data.title,
                        and  data.extract,

**Comment by Christophgru** [comment]
Idea Add exception handling around failing api calls

**Comment by Sickys** [comment]
Bei dem Wikipedia Code müssten eig schon fehlerhafte API Calls abgedeckt sein. Der Fall, dass keine Wikipedia Seite vorhanden ist wird auf jeden Fall abgefangen jetzt. Kannst das Issue als resolved markieren außer du willst mehr Error Handling
